# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Fullbleed-Commercial
from __future__ import annotations

from ._core import profile_registry
from .agency_letter import (
    AGENCY_LETTER_FAMILY_ID,
    FL_ESCAMBIA_AGENCY_NOTICE_LETTER_SINGLE_PAGE_CLERK_LETTERHEAD_NOTICE_V1,
    FL_ESCAMBIA_AGENCY_NOTICE_LETTER_SINGLE_PAGE_CLERK_LETTERHEAD_2021_V1,
    FL_ESCAMBIA_AGENCY_NOTICE_PUBLIC_NOTICE_VAB_RESCHEDULED_2020_V1,
)
from .court_motion_form import (
    COURT_MOTION_FORM_FAMILY_ID,
    FL_ESCAMBIA_COURT_MOTION_FORM_CHILD_SUPPORT_TELEPHONE_HEARING_TITLE_IV_D_2019_V1,
    FL_ESCAMBIA_COURT_MOTION_FORM_CLERK_DISCHARGE_FORFEITURE_FS903_26_8_2020_V1,
)
from .declaration_form import (
    DECLARATION_FORM_FAMILY_ID,
    FL_ESCAMBIA_DECLARATION_FORM_CDC_EVICTION_2020_LAYOUT_V1,
)
from .instruction_sheet import (
    INSTRUCTION_SHEET_FAMILY_ID,
    FL_ESCAMBIA_INSTRUCTION_SHEET_CHILD_SUPPORT_PHONE_TESTIMONY_2019_V1,
    FL_STATE_FAMILY_LAW_INSTRUCTION_PACKET_FORM_12_961_2018_V1,
    FL_STATE_FAMILY_LAW_INSTRUCTION_PACKET_FORM_12_921_2018_V1,
)
from .investment_portfolio_report import (
    FL_ESCAMBIA_INVESTMENT_PORTFOLIO_SUMMARY_FY2019_2020_NOV2019_V1,
    INVESTMENT_PORTFOLIO_REPORT_FAMILY_ID,
)
from .marriage_record import (
    FL_ESCAMBIA_MARRIAGE_RECORD_REV2016,
    FL_ESCAMBIA_MARRIAGE_RECORD_REV2019,
    MARRIAGE_RECORD_FAMILY_ID,
)
from .recorded_plat import (
    FL_ESCAMBIA_RECORDED_PLAT_LEGACY_SIDE_CERTIFICATE_LAYOUT_V1,
    FL_ESCAMBIA_RECORDED_PLAT_MODERN_ENGINEERING_MULTISHEET_LAYOUT_V1,
    FL_ESCAMBIA_RECORDED_PLAT_PB1_PG85_RENZ_ANNA_VILLA_EXEMPLAR_V1,
    FL_ESCAMBIA_RECORDED_PLAT_PB1_PG87_KUFRIANT_PARK_EXEMPLAR_V1,
    FL_ESCAMBIA_RECORDED_PLAT_PB1_PG89_SAUFLEY_HEIGHTS_EXEMPLAR_V1,
    FL_ESCAMBIA_RECORDED_PLAT_PB20_PG13B_PRESERVE_AT_DEER_RUN_PHASE_TWO_EXEMPLAR_V1,
    RECORDED_PLAT_FAMILY_ID,
)
from .redaction_request_form import (
    FL_ESCAMBIA_REQUEST_REDACTION_EXEMPT_PERSONAL_INFORMATION_EFFECTIVE_2025_V1,
    REQUEST_REDACTION_FORM_FAMILY_ID,
)
from .warranty_deed import FL_ESCAMBIA_WARRANTY_DEED_REV1994, WARRANTY_DEED_FAMILY_ID


REGISTRY = profile_registry(
    FL_ESCAMBIA_AGENCY_NOTICE_LETTER_SINGLE_PAGE_CLERK_LETTERHEAD_NOTICE_V1,
    FL_ESCAMBIA_AGENCY_NOTICE_PUBLIC_NOTICE_VAB_RESCHEDULED_2020_V1,
    FL_ESCAMBIA_COURT_MOTION_FORM_CHILD_SUPPORT_TELEPHONE_HEARING_TITLE_IV_D_2019_V1,
    FL_ESCAMBIA_COURT_MOTION_FORM_CLERK_DISCHARGE_FORFEITURE_FS903_26_8_2020_V1,
    FL_ESCAMBIA_DECLARATION_FORM_CDC_EVICTION_2020_LAYOUT_V1,
    FL_ESCAMBIA_INSTRUCTION_SHEET_CHILD_SUPPORT_PHONE_TESTIMONY_2019_V1,
    FL_ESCAMBIA_INVESTMENT_PORTFOLIO_SUMMARY_FY2019_2020_NOV2019_V1,
    FL_STATE_FAMILY_LAW_INSTRUCTION_PACKET_FORM_12_961_2018_V1,
    FL_STATE_FAMILY_LAW_INSTRUCTION_PACKET_FORM_12_921_2018_V1,
    FL_ESCAMBIA_MARRIAGE_RECORD_REV2016,
    FL_ESCAMBIA_MARRIAGE_RECORD_REV2019,
    FL_ESCAMBIA_RECORDED_PLAT_LEGACY_SIDE_CERTIFICATE_LAYOUT_V1,
    FL_ESCAMBIA_RECORDED_PLAT_MODERN_ENGINEERING_MULTISHEET_LAYOUT_V1,
    FL_ESCAMBIA_REQUEST_REDACTION_EXEMPT_PERSONAL_INFORMATION_EFFECTIVE_2025_V1,
    FL_ESCAMBIA_WARRANTY_DEED_REV1994,
)

__all__ = [
    "REGISTRY",
    "AGENCY_LETTER_FAMILY_ID",
    "COURT_MOTION_FORM_FAMILY_ID",
    "DECLARATION_FORM_FAMILY_ID",
    "INSTRUCTION_SHEET_FAMILY_ID",
    "INVESTMENT_PORTFOLIO_REPORT_FAMILY_ID",
    "MARRIAGE_RECORD_FAMILY_ID",
    "RECORDED_PLAT_FAMILY_ID",
    "REQUEST_REDACTION_FORM_FAMILY_ID",
    "WARRANTY_DEED_FAMILY_ID",
    "FL_ESCAMBIA_AGENCY_NOTICE_LETTER_SINGLE_PAGE_CLERK_LETTERHEAD_NOTICE_V1",
    "FL_ESCAMBIA_AGENCY_NOTICE_LETTER_SINGLE_PAGE_CLERK_LETTERHEAD_2021_V1",
    "FL_ESCAMBIA_AGENCY_NOTICE_PUBLIC_NOTICE_VAB_RESCHEDULED_2020_V1",
    "FL_ESCAMBIA_COURT_MOTION_FORM_CHILD_SUPPORT_TELEPHONE_HEARING_TITLE_IV_D_2019_V1",
    "FL_ESCAMBIA_COURT_MOTION_FORM_CLERK_DISCHARGE_FORFEITURE_FS903_26_8_2020_V1",
    "FL_ESCAMBIA_DECLARATION_FORM_CDC_EVICTION_2020_LAYOUT_V1",
    "FL_ESCAMBIA_INSTRUCTION_SHEET_CHILD_SUPPORT_PHONE_TESTIMONY_2019_V1",
    "FL_ESCAMBIA_INVESTMENT_PORTFOLIO_SUMMARY_FY2019_2020_NOV2019_V1",
    "FL_STATE_FAMILY_LAW_INSTRUCTION_PACKET_FORM_12_961_2018_V1",
    "FL_STATE_FAMILY_LAW_INSTRUCTION_PACKET_FORM_12_921_2018_V1",
    "FL_ESCAMBIA_MARRIAGE_RECORD_REV2016",
    "FL_ESCAMBIA_MARRIAGE_RECORD_REV2019",
    "FL_ESCAMBIA_RECORDED_PLAT_LEGACY_SIDE_CERTIFICATE_LAYOUT_V1",
    "FL_ESCAMBIA_RECORDED_PLAT_MODERN_ENGINEERING_MULTISHEET_LAYOUT_V1",
    "FL_ESCAMBIA_RECORDED_PLAT_PB1_PG85_RENZ_ANNA_VILLA_EXEMPLAR_V1",
    "FL_ESCAMBIA_RECORDED_PLAT_PB1_PG87_KUFRIANT_PARK_EXEMPLAR_V1",
    "FL_ESCAMBIA_RECORDED_PLAT_PB1_PG89_SAUFLEY_HEIGHTS_EXEMPLAR_V1",
    "FL_ESCAMBIA_RECORDED_PLAT_PB20_PG13B_PRESERVE_AT_DEER_RUN_PHASE_TWO_EXEMPLAR_V1",
    "FL_ESCAMBIA_REQUEST_REDACTION_EXEMPT_PERSONAL_INFORMATION_EFFECTIVE_2025_V1",
    "FL_ESCAMBIA_WARRANTY_DEED_REV1994",
]
