# SPDX-License-Identifier: MIT
"""Public Python facade for Fullbleed's dependency-free native ABI.

The compiled module deliberately exposes one small stable-ABI dispatcher.  This
module preserves the public API that was previously generated by the binding layer while
keeping native capsule handles private.
"""

from . import _fullbleed as _native


def _call(handle, operation, *payload):
    return _native._dispatch(handle, operation, payload)


def _require_string(value, name):
    if not isinstance(value, str):
        raise TypeError(f"{name} must be a string")


def _require_optional_string(value, name):
    if value is not None:
        _require_string(value, name)


def _as_float(value, name):
    if not isinstance(value, (int, float)) and not hasattr(type(value), "__float__"):
        raise TypeError(f"{name} must be a real number")
    try:
        return float(value)
    except TypeError as error:
        raise TypeError(f"{name} must be a real number") from error


class _NativeFacadeType(type):
    def __new__(metaclass, name, bases, namespace, **kwargs):
        for base in bases:
            if isinstance(base, _NativeFacadeType):
                raise TypeError(
                    f"type '{base.__module__}.{base.__name__}' is not an acceptable base type"
                )
        return super().__new__(metaclass, name, bases, namespace, **kwargs)


class AssetKind(metaclass=_NativeFacadeType):
    Css = "css"
    Font = "font"
    Image = "image"
    Pdf = "pdf"
    Svg = "svg"
    Other = "other"

    def __new__(cls, /, *args, **kwargs):
        raise TypeError("No constructor defined for AssetKind")


class Asset(metaclass=_NativeFacadeType):
    __slots__ = ("_handle",)

    def __init__(self, /):
        raise TypeError("No constructor defined for Asset")

    @classmethod
    def _from_handle(cls, /, handle):
        instance = object.__new__(cls)
        instance._handle = handle
        return instance

    def info(self, /):
        return _call(self._handle, "Asset.info")


class AssetBundle(metaclass=_NativeFacadeType):
    __slots__ = ("_handle",)

    def __init__(self, /):
        self._handle = _call(None, "AssetBundle.new")

    def add(self, /, asset):
        if not isinstance(asset, Asset):
            raise TypeError("asset must be an Asset")
        return _call(self._handle, "AssetBundle.add", asset._handle)

    def add_file(self, /, path, kind, name=None, trusted=False, remote=False):
        handle = _call(
            self._handle,
            "AssetBundle.add_file",
            path,
            kind,
            name,
            trusted,
            remote,
        )
        return Asset._from_handle(handle)

    def css(self, /):
        return _call(self._handle, "AssetBundle.css")

    def assets_info(self, /):
        return _call(self._handle, "AssetBundle.assets_info")


class WatermarkSpec(metaclass=_NativeFacadeType):
    __slots__ = (
        "_kind",
        "_value",
        "_layer",
        "_semantics",
        "_opacity",
        "_rotation_deg",
        "_font_name",
        "_font_size",
        "_color",
    )

    def __init__(
        self,
        /,
        kind,
        value,
        layer="overlay",
        semantics=None,
        opacity=0.15,
        rotation_deg=0.0,
        font_name=None,
        font_size=None,
        color=None,
    ):
        _require_string(kind, "kind")
        _require_string(value, "value")
        _require_string(layer, "layer")
        _require_optional_string(semantics, "semantics")
        opacity = _as_float(opacity, "opacity")
        rotation_deg = _as_float(rotation_deg, "rotation_deg")
        _require_optional_string(font_name, "font_name")
        if font_size is not None:
            font_size = _as_float(font_size, "font_size")
        _require_optional_string(color, "color")
        self._kind = kind
        self._value = value
        self._layer = layer
        self._semantics = semantics
        self._opacity = opacity
        self._rotation_deg = rotation_deg
        self._font_name = font_name
        self._font_size = font_size
        self._color = color

    def _native_payload(self, /):
        return {
            "kind": self._kind,
            "value": self._value,
            "layer": self._layer,
            "semantics": self._semantics,
            "opacity": self._opacity,
            "rotation_deg": self._rotation_deg,
            "font_name": self._font_name,
            "font_size": self._font_size,
            "color": self._color,
        }


class PdfEngine(metaclass=_NativeFacadeType):
    __slots__ = ("_handle",)

    def __init__(
        self,
        /,
        page_width=None,
        page_height=None,
        margin=None,
        page_margins=None,
        font_dirs=None,
        font_files=None,
        reuse_xobjects=True,
        svg_form_xobjects=False,
        svg_raster_fallback=False,
        unicode_support=True,
        shape_text=True,
        unicode_metrics=True,
        pdf_version=None,
        pdf_profile=None,
        output_intent_icc=None,
        output_intent_identifier=None,
        output_intent_info=None,
        output_intent_components=None,
        color_space=None,
        document_lang=None,
        document_title=None,
        header_first=None,
        header_each=None,
        header_last=None,
        header_x=None,
        header_y_from_top=None,
        header_font_name=None,
        header_font_size=None,
        header_color=None,
        header_html_first=None,
        header_html_each=None,
        header_html_last=None,
        header_html_x=None,
        header_html_y_from_top=None,
        header_html_width=None,
        header_html_height=None,
        footer_first=None,
        footer_each=None,
        footer_last=None,
        footer_x=None,
        footer_y_from_bottom=None,
        footer_font_name=None,
        footer_font_size=None,
        footer_color=None,
        watermark=None,
        watermark_text=None,
        watermark_html=None,
        watermark_image=None,
        watermark_layer="overlay",
        watermark_semantics="artifact",
        watermark_opacity=0.15,
        watermark_rotation=0.0,
        watermark_font_name=None,
        watermark_font_size=None,
        watermark_color=None,
        paginated_context=None,
        template_binding=None,
        layout_strategy=None,
        accept_lazy_layout_cost=False,
        lazy_max_passes=4,
        lazy_budget_ms=50.0,
        jit_mode=None,
        debug=False,
        debug_out=None,
        perf=False,
        perf_out=None,
    ):
        if watermark is not None:
            if not isinstance(watermark, WatermarkSpec):
                raise TypeError("watermark must be a WatermarkSpec instance or None")
            watermark = watermark._native_payload()
        self._handle = _call(
            None,
            "PdfEngine.new",
            page_width,
            page_height,
            margin,
            page_margins,
            font_dirs,
            font_files,
            reuse_xobjects,
            svg_form_xobjects,
            svg_raster_fallback,
            unicode_support,
            shape_text,
            unicode_metrics,
            pdf_version,
            pdf_profile,
            output_intent_icc,
            output_intent_identifier,
            output_intent_info,
            output_intent_components,
            color_space,
            document_lang,
            document_title,
            header_first,
            header_each,
            header_last,
            header_x,
            header_y_from_top,
            header_font_name,
            header_font_size,
            header_color,
            header_html_first,
            header_html_each,
            header_html_last,
            header_html_x,
            header_html_y_from_top,
            header_html_width,
            header_html_height,
            footer_first,
            footer_each,
            footer_last,
            footer_x,
            footer_y_from_bottom,
            footer_font_name,
            footer_font_size,
            footer_color,
            watermark,
            watermark_text,
            watermark_html,
            watermark_image,
            watermark_layer,
            watermark_semantics,
            watermark_opacity,
            watermark_rotation,
            watermark_font_name,
            watermark_font_size,
            watermark_color,
            paginated_context,
            template_binding,
            layout_strategy,
            accept_lazy_layout_cost,
            lazy_max_passes,
            lazy_budget_ms,
            jit_mode,
            debug,
            debug_out,
            perf,
            perf_out,
        )

    @property
    def document_lang(self, /):
        return _call(self._handle, "PdfEngine.get_document_lang")

    @document_lang.setter
    def document_lang(self, value, /):
        _call(self._handle, "PdfEngine.set_document_lang", value)

    @property
    def document_title(self, /):
        return _call(self._handle, "PdfEngine.get_document_title")

    @document_title.setter
    def document_title(self, value, /):
        _call(self._handle, "PdfEngine.set_document_title", value)

    @property
    def document_css_href(self, /):
        return _call(self._handle, "PdfEngine.get_document_css_href")

    @document_css_href.setter
    def document_css_href(self, value, /):
        _call(self._handle, "PdfEngine.set_document_css_href", value)

    @property
    def document_css_source_path(self, /):
        return _call(self._handle, "PdfEngine.get_document_css_source_path")

    @document_css_source_path.setter
    def document_css_source_path(self, value, /):
        _call(self._handle, "PdfEngine.set_document_css_source_path", value)

    @property
    def document_css_media(self, /):
        return _call(self._handle, "PdfEngine.get_document_css_media")

    @document_css_media.setter
    def document_css_media(self, value, /):
        _call(self._handle, "PdfEngine.set_document_css_media", value)

    @property
    def document_css_required(self, /):
        return _call(self._handle, "PdfEngine.get_document_css_required")

    @document_css_required.setter
    def document_css_required(self, value, /):
        _call(self._handle, "PdfEngine.set_document_css_required", value)

    def register_bundle(self, /, bundle):
        if not isinstance(bundle, AssetBundle):
            raise TypeError("bundle must be an AssetBundle")
        return _call(self._handle, "PdfEngine.register_bundle", bundle._handle)

    def document_metadata(self, /):
        return _call(self._handle, "PdfEngine.document_metadata")

    def emit_html(self, /, html, out_path, wrap_document=True):
        return _call(self._handle, "PdfEngine.emit_html", html, out_path, wrap_document)

    def emit_css(self, /, css, out_path):
        return _call(self._handle, "PdfEngine.emit_css", css, out_path)

    def emit_artifacts(self, /, html, css, html_path, css_path, wrap_document=True):
        return _call(
            self._handle,
            "PdfEngine.emit_artifacts",
            html,
            css,
            html_path,
            css_path,
            wrap_document,
        )

    def verify_accessibility_html(
        self,
        /,
        html,
        css="",
        profile="strict",
        mode="error",
        render_preview_png_path=None,
        a11y_report=None,
        claim_evidence=None,
        pagination_trace_summary=None,
        diagnostic_signals=None,
    ):
        return _call(
            self._handle,
            "PdfEngine.verify_accessibility_html",
            html,
            css,
            profile,
            mode,
            render_preview_png_path,
            a11y_report,
            claim_evidence,
            pagination_trace_summary,
            diagnostic_signals,
        )

    def verify_accessibility_artifacts(
        self,
        /,
        html_path,
        css_path,
        profile="strict",
        mode="error",
        render_preview_png_path=None,
        a11y_report=None,
        claim_evidence=None,
        pagination_trace_summary=None,
        diagnostic_signals=None,
    ):
        return _call(
            self._handle,
            "PdfEngine.verify_accessibility_artifacts",
            html_path,
            css_path,
            profile,
            mode,
            render_preview_png_path,
            a11y_report,
            claim_evidence,
            pagination_trace_summary,
            diagnostic_signals,
        )

    def verify_paged_media_rank_html(
        self,
        /,
        html,
        css="",
        profile="strict",
        mode="error",
        overflow_count=None,
        known_loss_count=None,
        source_page_count=None,
        render_page_count=None,
        review_queue_items=None,
        pagination_trace_summary=None,
        diagnostic_signals=None,
    ):
        return _call(
            self._handle,
            "PdfEngine.verify_paged_media_rank_html",
            html,
            css,
            profile,
            mode,
            overflow_count,
            known_loss_count,
            source_page_count,
            render_page_count,
            review_queue_items,
            pagination_trace_summary,
            diagnostic_signals,
        )

    def verify_paged_media_rank_artifacts(
        self,
        /,
        html_path,
        css_path,
        profile="strict",
        mode="error",
        overflow_count=None,
        known_loss_count=None,
        source_page_count=None,
        render_page_count=None,
        review_queue_items=None,
        pagination_trace_summary=None,
        diagnostic_signals=None,
    ):
        return _call(
            self._handle,
            "PdfEngine.verify_paged_media_rank_artifacts",
            html_path,
            css_path,
            profile,
            mode,
            overflow_count,
            known_loss_count,
            source_page_count,
            render_page_count,
            review_queue_items,
            pagination_trace_summary,
            diagnostic_signals,
        )

    def render_pdf(self, /, html, css, deterministic_hash=None):
        return _call(self._handle, "PdfEngine.render_pdf", html, css, deterministic_hash)

    def render_image_pages(self, /, html, css, dpi=150):
        return _call(self._handle, "PdfEngine.render_image_pages", html, css, dpi)

    def render_image_pages_to_dir(self, /, html, css, out_dir, dpi=150, stem=None):
        return _call(
            self._handle,
            "PdfEngine.render_image_pages_to_dir",
            html,
            css,
            out_dir,
            dpi,
            stem,
        )

    def render_finalized_pdf_image_pages(self, /, pdf_path, dpi=150):
        return _call(
            self._handle,
            "PdfEngine.render_finalized_pdf_image_pages",
            pdf_path,
            dpi,
        )

    def render_finalized_pdf_image_pages_to_dir(
        self, /, pdf_path, out_dir, dpi=150, stem=None
    ):
        return _call(
            self._handle,
            "PdfEngine.render_finalized_pdf_image_pages_to_dir",
            pdf_path,
            out_dir,
            dpi,
            stem,
        )

    def render_pdf_with_page_data(self, /, html, css):
        return _call(self._handle, "PdfEngine.render_pdf_with_page_data", html, css)

    def render_pdf_with_page_data_and_glyph_report(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_with_page_data_and_glyph_report",
            html,
            css,
        )

    def export_render_time_reading_order_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_reading_order_trace",
            html,
            css,
        )

    def export_render_time_structure_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_structure_trace",
            html,
            css,
        )

    def export_render_time_font_resolution_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_font_resolution_trace",
            html,
            css,
        )

    def export_render_time_asset_resolution_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_asset_resolution_trace",
            html,
            css,
        )

    def export_render_time_pagination_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_pagination_trace",
            html,
            css,
        )

    def export_render_time_typography_drift_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_typography_drift_trace",
            html,
            css,
        )

    def export_render_time_region_text_alignment_trace(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.export_render_time_region_text_alignment_trace",
            html,
            css,
        )

    def render_pdf_with_page_data_and_template_bindings(self, /, html, css):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_with_page_data_and_template_bindings",
            html,
            css,
        )

    def render_pdf_with_page_data_and_template_bindings_and_glyph_report(
        self, /, html, css
    ):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_with_page_data_and_template_bindings_and_glyph_report",
            html,
            css,
        )

    def plan_template_compose(self, /, html, css, templates, dx=0.0, dy=0.0):
        return _call(
            self._handle,
            "PdfEngine.plan_template_compose",
            html,
            css,
            templates,
            dx,
            dy,
        )

    def render_pdf_with_glyph_report(self, /, html, css):
        return _call(self._handle, "PdfEngine.render_pdf_with_glyph_report", html, css)

    def render_pdf_with_glyph_report_and_render_time_reading_order_trace(
        self, /, html, css
    ):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_with_glyph_report_and_render_time_reading_order_trace",
            html,
            css,
        )

    def render_pdf_to_file(self, /, html, css, path, deterministic_hash=None):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_to_file",
            html,
            css,
            path,
            deterministic_hash,
        )

    def render_pdf_batch(self, /, html_list, css, deterministic_hash=None):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch",
            html_list,
            css,
            deterministic_hash,
        )

    def render_pdf_batch_to_file(self, /, html_list, css, path, deterministic_hash=None):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch_to_file",
            html_list,
            css,
            path,
            deterministic_hash,
        )

    def render_pdf_batch_with_css(self, /, jobs, deterministic_hash=None):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch_with_css",
            jobs,
            deterministic_hash,
        )

    def render_pdf_batch_with_css_to_file(self, /, jobs, path, deterministic_hash=None):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch_with_css_to_file",
            jobs,
            path,
            deterministic_hash,
        )

    def render_pdf_batch_parallel(self, /, html_list, css, deterministic_hash=None):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch_parallel",
            html_list,
            css,
            deterministic_hash,
        )

    def render_pdf_batch_to_file_parallel_with_page_data(
        self, /, html_list, css, path, deterministic_hash=None
    ):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch_to_file_parallel_with_page_data",
            html_list,
            css,
            path,
            deterministic_hash,
        )

    def render_pdf_batch_to_file_parallel(
        self, /, html_list, css, path, deterministic_hash=None
    ):
        return _call(
            self._handle,
            "PdfEngine.render_pdf_batch_to_file_parallel",
            html_list,
            css,
            path,
            deterministic_hash,
        )


def build_features():
    return _call(None, "build_features")


def inspect_pdf(path):
    return _call(None, "inspect_pdf", path)


def extract_pdf_page_texts(pdf_path):
    return _call(None, "extract_pdf_page_texts", pdf_path)


def export_pdf_reading_order_trace(pdf_path):
    return _call(None, "export_pdf_reading_order_trace", pdf_path)


def export_pdf_structure_trace(pdf_path):
    return _call(None, "export_pdf_structure_trace", pdf_path)


def verify_pdf_ua_seed(pdf_path, mode="error"):
    return _call(None, "verify_pdf_ua_seed", pdf_path, mode)


def inspect_template_catalog(templates):
    return _call(None, "inspect_template_catalog", templates)


def vendored_asset(source, kind, name=None, trusted=False, remote=False):
    handle = _call(None, "vendored_asset", source, kind, name, trusted, remote)
    return Asset._from_handle(handle)


def fetch_asset(url):
    return _call(None, "fetch_asset", url)


def concat_css(parts):
    return _call(None, "concat_css", parts)


def finalize_stamp_pdf(template, overlay, out, page_map=None, dx=0.0, dy=0.0):
    return _call(None, "finalize_stamp_pdf", template, overlay, out, page_map, dx, dy)


def finalize_compose_pdf(templates, plan, overlay, out, annotation_mode=None):
    return _call(
        None,
        "finalize_compose_pdf",
        templates,
        plan,
        overlay,
        out,
        annotation_mode,
    )


def audit_contract_metadata():
    return _call(None, "audit_contract_metadata")


def audit_contract_registry(name):
    return _call(None, "audit_contract_registry", name)


def audit_contract_wcag20aa_coverage(findings):
    return _call(None, "audit_contract_wcag20aa_coverage", findings)


def audit_contract_section508_html_coverage(findings):
    return _call(None, "audit_contract_section508_html_coverage", findings)


def audit_contrast_render_png(png_path):
    return _call(None, "audit_contrast_render_png", png_path)


def audit_sparse_page_visual_pair(source_png_path, render_png_path):
    return _call(
        None,
        "audit_sparse_page_visual_pair",
        source_png_path,
        render_png_path,
    )


__all__ = [
    "PdfEngine",
    "AssetKind",
    "Asset",
    "AssetBundle",
    "WatermarkSpec",
    "inspect_pdf",
    "build_features",
    "inspect_template_catalog",
    "vendored_asset",
    "fetch_asset",
    "concat_css",
    "audit_contract_metadata",
    "audit_contract_registry",
    "audit_contract_wcag20aa_coverage",
    "audit_contract_section508_html_coverage",
    "audit_contrast_render_png",
    "audit_sparse_page_visual_pair",
    "extract_pdf_page_texts",
    "export_pdf_reading_order_trace",
    "export_pdf_structure_trace",
    "verify_pdf_ua_seed",
    "finalize_stamp_pdf",
    "finalize_compose_pdf",
]


_CLASS_NAMES = {"PdfEngine", "AssetKind", "Asset", "AssetBundle", "WatermarkSpec"}
for _name in __all__:
    globals()[_name].__module__ = (
        "builtins" if _name in _CLASS_NAMES else "fullbleed._fullbleed"
    )
