#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate native Standard 14 preview metrics from pinned Adobe data."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "tools/data/base14"
TARGET = ROOT / "src/base14_metrics_data.rs"


def rust_string(text):
    return '"' + ''.join(c if 32 <= ord(c) < 127 and c not in '\\"' else f'\\u{{{ord(c):x}}}' for c in text) + '"'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sources = json.loads((DATA / "sources.json").read_text(encoding="utf-8"))
    for name, expected in sources["files"].items():
        raw = (DATA / name).read_bytes()
        assert len(raw) == expected["bytes"] and hashlib.sha256(raw).hexdigest() == expected["sha256"], name
    mappings = {}
    for filename in ["agl-glyphlist.txt", "agl-zapfdingbats.txt"]:
        for line in (DATA / filename).read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#"):
                continue
            name, codes = line.split(";")
            mappings[name] = ''.join(chr(int(code, 16)) for code in codes.split())
    fonts = {}
    notices = set()
    for path in sorted(DATA.glob("*.afm")):
        content = path.read_text(encoding="latin-1")
        name = re.search(r"^FontName (.+)$", content, re.M).group(1).strip()
        glyphs = {}
        encoding = {}
        for line in content.splitlines():
            if line.startswith("Notice ") or line.startswith("Comment Copyright"):
                notices.add(line.removeprefix("Notice ").removeprefix("Comment ").strip())
            if not line.startswith("C "):
                continue
            fields = dict(part.strip().split(" ", 1) for part in line.split(";") if part.strip())
            glyph = fields["N"]
            assert glyph in mappings, (name, glyph)
            width = int(fields["WX"])
            assert 0 <= width <= 65535
            glyphs[glyph] = (mappings[glyph], width)
            code = int(fields["C"])
            if code >= 0:
                assert code <= 255 and code not in encoding
                encoding[code] = glyph
        assert len(glyphs) == int(re.search(r"^StartCharMetrics (\d+)", content, re.M).group(1))
        fonts[name] = (glyphs, encoding)
    assert len(fonts) == 14
    license_notice = (ROOT / "THIRD_PARTY_LICENSES.md").read_text(encoding="utf-8")
    for notice in notices:
        assert notice in license_notice, "Missing AFM redistribution notice: " + notice
    assert (DATA / "agl-LICENSE.md").read_text(encoding="utf-8").strip() in license_notice
    assert "Copyright 2002-2019 Adobe (http://www.adobe.com/)." in license_notice
    permission = re.search(r"This file and the 14 PostScript.*?AFM files\.",
                           (DATA / "MustRead.html").read_text(encoding="utf-8")).group(0)
    assert permission in license_notice, "Missing original AFM permission paragraph"
    lines = ["// Generated by tools/generate_base14_metrics.py; do not edit by hand.",
             "// Derived from Adobe Core 14 AFMs and Adobe Glyph List data.",
             "// Adobe Glyph List: Copyright 2002-2019 Adobe (http://www.adobe.com/).",
             "// Modification: retain widths/encodings and convert them into Rust lookup tables.",
             "// Original notices and redistribution terms: THIRD_PARTY_LICENSES.md."]
    lines += ["// " + notice for notice in sorted(notices)]
    lines += ["", "use super::{Base14Font, GlyphMetric};", "", "#[rustfmt::skip]",
              "pub(super) fn font(name: &str) -> Option<Base14Font> {", "    match name {"]
    for name in fonts:
        symbol = name.upper().replace("-", "_")
        lines += [f'        "{name}" => Some(Base14Font {{ glyphs: {symbol}_GLYPHS, unicode: {symbol}_UNICODE, builtin: &{symbol}_ENCODING }}),']
    lines += ["        _ => None,", "    }", "}", ""]
    for name, (glyphs, encoding) in fonts.items():
        symbol = name.upper().replace("-", "_")
        ordered = sorted(glyphs)
        indices = {glyph: index for index, glyph in enumerate(ordered)}
        lines += ["#[rustfmt::skip]", f"const {symbol}_GLYPHS: &[GlyphMetric] = &["]
        for glyph in ordered:
            unicode, width = glyphs[glyph]
            lines += [f"    GlyphMetric {{ name: {rust_string(glyph)}, text: {rust_string(unicode)}, width: {width} }},"]
        lines += ["];", "#[rustfmt::skip]", f"const {symbol}_UNICODE: &[(u32, u16)] = &["]
        unicode_indices = {}
        for glyph in ordered:
            text, width = glyphs[glyph]
            if len(text) == 1:
                code = ord(text)
                if code in unicode_indices:
                    assert glyphs[ordered[unicode_indices[code]]][1] == width, (name, glyph)
                unicode_indices[code] = indices[glyph]
        for code, index in sorted(unicode_indices.items()):
            lines += [f"    (0x{code:04x}, {index}),"]
        lines += ["];", "#[rustfmt::skip]", f"const {symbol}_ENCODING: [u16; 256] = ["]
        for offset in range(0, 256, 16):
            values = [str(indices[encoding[code]] + 1) if code in encoding else "0" for code in range(offset, offset + 16)]
            lines += ["    " + ", ".join(values) + ","]
        lines += ["];", ""]
    expected = ('\n'.join(lines)).encode("utf-8")
    if args.check:
        assert TARGET.read_bytes() == expected, "Base14 metric tables need regeneration"
    else:
        TARGET.write_bytes(expected)
    print(json.dumps({"ok": True, "fonts": len(fonts), "glyphs": sum(len(g[0]) for g in fonts.values()),
                      "sha256": hashlib.sha256(expected).hexdigest(), "check": args.check}))


if __name__ == "__main__":
    main()
